create table countries (
	code VARCHAR(50),
	country_name VARCHAR(50),
	region_id INT
);
insert into countries (code, country_name, region_id) values ('CN', 'China', 7);
insert into countries (code, country_name, region_id) values ('MX', 'Mexico', 7);
insert into countries (code, country_name, region_id) values ('CN', 'China', 10);
insert into countries (code, country_name, region_id) values ('MN', 'Mongolia', 2);
insert into countries (code, country_name, region_id) values ('CN', 'China', 8);
insert into countries (code, country_name, region_id) values ('RU', 'Russia', 7);
insert into countries (code, country_name, region_id) values ('CN', 'China', 3);
insert into countries (code, country_name, region_id) values ('GP', 'Guadeloupe', 1);
insert into countries (code, country_name, region_id) values ('FO', 'Faroe Islands', 2);
insert into countries (code, country_name, region_id) values ('FR', 'France', 6);
insert into countries (code, country_name, region_id) values ('ID', 'Indonesia', 10);
insert into countries (code, country_name, region_id) values ('PH', 'Philippines', 2);
insert into countries (code, country_name, region_id) values ('CN', 'China', 2);
insert into countries (code, country_name, region_id) values ('PH', 'Philippines', 2);
insert into countries (code, country_name, region_id) values ('CN', 'China', 8);
insert into countries (code, country_name, region_id) values ('LK', 'Sri Lanka', 9);
insert into countries (code, country_name, region_id) values ('IT', 'Italy', 9);
insert into countries (code, country_name, region_id) values ('RU', 'Russia', 7);
insert into countries (code, country_name, region_id) values ('ID', 'Indonesia', 1);
insert into countries (code, country_name, region_id) values ('CR', 'Costa Rica', 7);
insert into countries (code, country_name, region_id) values ('SY', 'Syria', 8);
insert into countries (code, country_name, region_id) values ('LU', 'Luxembourg', 4);
insert into countries (code, country_name, region_id) values ('RU', 'Russia', 10);
insert into countries (code, country_name, region_id) values ('CN', 'China', 3);
insert into countries (code, country_name, region_id) values ('PH', 'Philippines', 5);
insert into countries (code, country_name, region_id) values ('BW', 'Botswana', 6);
insert into countries (code, country_name, region_id) values ('CN', 'China', 7);
insert into countries (code, country_name, region_id) values ('TH', 'Thailand', 3);
insert into countries (code, country_name, region_id) values ('EC', 'Ecuador', 9);
insert into countries (code, country_name, region_id) values ('US', 'United States', 10);
insert into countries (code, country_name, region_id) values ('CN', 'China', 6);
insert into countries (code, country_name, region_id) values ('PL', 'Poland', 3);
insert into countries (code, country_name, region_id) values ('ID', 'Indonesia', 10);
insert into countries (code, country_name, region_id) values ('CZ', 'Czech Republic', 7);
insert into countries (code, country_name, region_id) values ('SI', 'Slovenia', 1);
insert into countries (code, country_name, region_id) values ('PH', 'Philippines', 3);
insert into countries (code, country_name, region_id) values ('PL', 'Poland', 2);
insert into countries (code, country_name, region_id) values ('PL', 'Poland', 9);
insert into countries (code, country_name, region_id) values ('FR', 'France', 4);
insert into countries (code, country_name, region_id) values ('CN', 'China', 7);
insert into countries (code, country_name, region_id) values ('MM', 'Myanmar', 7);
insert into countries (code, country_name, region_id) values ('MX', 'Mexico', 2);
insert into countries (code, country_name, region_id) values ('ID', 'Indonesia', 1);
insert into countries (code, country_name, region_id) values ('NA', 'Namibia', 3);
insert into countries (code, country_name, region_id) values ('CN', 'China', 6);
insert into countries (code, country_name, region_id) values ('US', 'United States', 6);
insert into countries (code, country_name, region_id) values ('CN', 'China', 8);
insert into countries (code, country_name, region_id) values ('MT', 'Malta', 7);
insert into countries (code, country_name, region_id) values ('CN', 'China', 4);
insert into countries (code, country_name, region_id) values ('PL', 'Poland', 10);
select * from countries;
